apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-config" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}